-- CreateEnum
CREATE TYPE "Industry" AS ENUM ('E_COMMERCE', 'FOOD_BEVERAGE', 'FASHION_BEAUTY', 'TECHNOLOGY', 'FINANCE', 'HEALTH_WELLNESS', 'ENTERTAINMENT', 'EDUCATION', 'TRAVEL_HOSPITALITY', 'OTHER');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "companyName" TEXT,
ADD COLUMN     "industry" "Industry";
